from __future__ import annotations

from src.tools.models import Dish, NutritionInfo

MOCK_CATALOG: list[Dish] = [
    Dish(
        id="white_rice",
        name="Com trang",
        category="staple",
        ingredients=["gao"],
        allergens=[],
        cost_per_serving_vnd=4000,
        nutrition_per_serving=NutritionInfo(calories=220, protein_g=4.0, fiber_g=0.6),
        tags=[],
    ),
    Dish(
        id="brown_rice",
        name="Com gao lut",
        category="staple",
        ingredients=["gao lut"],
        allergens=[],
        cost_per_serving_vnd=4400,
        nutrition_per_serving=NutritionInfo(calories=215, protein_g=4.5, fiber_g=1.8),
        tags=[],
    ),
    Dish(
        id="mixed_grain_rice",
        name="Com ngu coc",
        category="staple",
        ingredients=["gao", "hat ngu coc"],
        allergens=[],
        cost_per_serving_vnd=4600,
        nutrition_per_serving=NutritionInfo(calories=225, protein_g=4.8, fiber_g=1.9),
        tags=[],
    ),
    Dish(
        id="turmeric_rice",
        name="Com nghe",
        category="staple",
        ingredients=["gao", "nghe"],
        allergens=[],
        cost_per_serving_vnd=4300,
        nutrition_per_serving=NutritionInfo(calories=218, protein_g=4.1, fiber_g=0.8),
        tags=[],
    ),
    Dish(
        id="sesame_rice",
        name="Com me den",
        category="staple",
        ingredients=["gao", "me den"],
        allergens=["sesame"],
        cost_per_serving_vnd=4500,
        nutrition_per_serving=NutritionInfo(calories=222, protein_g=4.4, fiber_g=1.2),
        tags=[],
    ),
    Dish(
        id="braised_pork_with_egg",
        name="Thit kho trung",
        category="main",
        ingredients=["thit heo", "trung", "nuoc mam"],
        allergens=["egg"],
        cost_per_serving_vnd=11800,
        nutrition_per_serving=NutritionInfo(calories=205, protein_g=14.5, fiber_g=0.3),
        tags=[],
    ),
    Dish(
        id="ginger_chicken",
        name="Ga kho gung",
        category="main",
        ingredients=["ga", "gung"],
        allergens=[],
        cost_per_serving_vnd=11200,
        nutrition_per_serving=NutritionInfo(calories=195, protein_g=15.0, fiber_g=0.4),
        tags=[],
    ),
    Dish(
        id="tomato_basa",
        name="Ca basa sot ca chua",
        category="main",
        ingredients=["ca basa", "ca chua"],
        allergens=["fish"],
        cost_per_serving_vnd=10900,
        nutrition_per_serving=NutritionInfo(calories=188, protein_g=15.5, fiber_g=0.7),
        tags=[],
    ),
    Dish(
        id="beef_onion",
        name="Bo xao hanh tay",
        category="main",
        ingredients=["thit bo", "hanh tay"],
        allergens=[],
        cost_per_serving_vnd=12300,
        nutrition_per_serving=NutritionInfo(calories=215, protein_g=16.0, fiber_g=0.8),
        tags=[],
    ),
    Dish(
        id="tofu_meat_sauce",
        name="Dau hu sot thit",
        category="main",
        ingredients=["dau hu", "thit bam"],
        allergens=["soy"],
        cost_per_serving_vnd=9800,
        nutrition_per_serving=NutritionInfo(calories=176, protein_g=13.0, fiber_g=1.4),
        tags=[],
    ),
    Dish(
        id="grilled_pork",
        name="Thit heo nuong",
        category="main",
        ingredients=["thit heo", "toi"],
        allergens=[],
        cost_per_serving_vnd=10800,
        nutrition_per_serving=NutritionInfo(calories=198, protein_g=14.2, fiber_g=0.3),
        tags=[],
    ),
    Dish(
        id="crispy_fish_fillet",
        name="Ca chien gion",
        category="main",
        ingredients=["ca phillet", "bot chien"],
        allergens=["fish", "gluten"],
        cost_per_serving_vnd=10600,
        nutrition_per_serving=NutritionInfo(calories=210, protein_g=14.0, fiber_g=0.5),
        tags=["fried"],
    ),
    Dish(
        id="garlic_mustard_greens",
        name="Cai xanh xao toi",
        category="vegetable",
        ingredients=["cai xanh", "toi"],
        allergens=[],
        cost_per_serving_vnd=3400,
        nutrition_per_serving=NutritionInfo(calories=58, protein_g=2.1, fiber_g=2.7),
        tags=[],
    ),
    Dish(
        id="stir_fried_chayote",
        name="Su su xao",
        category="vegetable",
        ingredients=["su su", "toi"],
        allergens=[],
        cost_per_serving_vnd=3200,
        nutrition_per_serving=NutritionInfo(calories=52, protein_g=1.6, fiber_g=2.5),
        tags=[],
    ),
    Dish(
        id="carrot_green_beans",
        name="Ca rot dau que xao",
        category="vegetable",
        ingredients=["ca rot", "dau que"],
        allergens=[],
        cost_per_serving_vnd=3600,
        nutrition_per_serving=NutritionInfo(calories=63, protein_g=2.0, fiber_g=2.9),
        tags=[],
    ),
    Dish(
        id="steamed_pumpkin",
        name="Bi do hap",
        category="vegetable",
        ingredients=["bi do"],
        allergens=[],
        cost_per_serving_vnd=3300,
        nutrition_per_serving=NutritionInfo(calories=55, protein_g=1.7, fiber_g=2.3),
        tags=[],
    ),
    Dish(
        id="bok_choy_garlic",
        name="Cai thia xao toi",
        category="vegetable",
        ingredients=["cai thia", "toi"],
        allergens=[],
        cost_per_serving_vnd=3500,
        nutrition_per_serving=NutritionInfo(calories=57, protein_g=2.2, fiber_g=2.6),
        tags=[],
    ),
    Dish(
        id="buttered_corn",
        name="Bap xao bo",
        category="vegetable",
        ingredients=["bap", "bo"],
        allergens=["milk"],
        cost_per_serving_vnd=3900,
        nutrition_per_serving=NutritionInfo(calories=78, protein_g=2.1, fiber_g=2.2),
        tags=[],
    ),
    Dish(
        id="pumpkin_minced_pork_soup",
        name="Canh bi do thit bam",
        category="soup",
        ingredients=["bi do", "thit bam"],
        allergens=[],
        cost_per_serving_vnd=3100,
        nutrition_per_serving=NutritionInfo(calories=60, protein_g=3.6, fiber_g=1.6),
        tags=[],
    ),
    Dish(
        id="cabbage_meat_soup",
        name="Canh bap cai nau thit",
        category="soup",
        ingredients=["bap cai", "thit heo"],
        allergens=[],
        cost_per_serving_vnd=3000,
        nutrition_per_serving=NutritionInfo(calories=54, protein_g=3.4, fiber_g=1.5),
        tags=[],
    ),
    Dish(
        id="amaranth_shrimp_soup",
        name="Canh mong toi nau tom",
        category="soup",
        ingredients=["mong toi", "tom"],
        allergens=["shellfish"],
        cost_per_serving_vnd=3400,
        nutrition_per_serving=NutritionInfo(calories=57, protein_g=4.0, fiber_g=1.7),
        tags=[],
    ),
    Dish(
        id="mustard_green_tofu_soup",
        name="Canh cai ngot dau hu",
        category="soup",
        ingredients=["cai ngot", "dau hu"],
        allergens=["soy"],
        cost_per_serving_vnd=2900,
        nutrition_per_serving=NutritionInfo(calories=49, protein_g=3.1, fiber_g=1.5),
        tags=[],
    ),
    Dish(
        id="spinach_meat_soup",
        name="Canh rau bina nau thit",
        category="soup",
        ingredients=["rau bina", "thit heo"],
        allergens=[],
        cost_per_serving_vnd=3200,
        nutrition_per_serving=NutritionInfo(calories=52, protein_g=3.5, fiber_g=1.8),
        tags=[],
    ),
    Dish(
        id="creamy_corn_soup",
        name="Sup bap kem",
        category="soup",
        ingredients=["bap", "sua"],
        allergens=["milk"],
        cost_per_serving_vnd=3600,
        nutrition_per_serving=NutritionInfo(calories=84, protein_g=3.0, fiber_g=1.4),
        tags=[],
    ),
    Dish(
        id="banana",
        name="Chuoi",
        category="fruit",
        ingredients=["chuoi"],
        allergens=[],
        cost_per_serving_vnd=3600,
        nutrition_per_serving=NutritionInfo(calories=89, protein_g=1.1, fiber_g=2.6),
        tags=[],
    ),
    Dish(
        id="orange",
        name="Cam",
        category="fruit",
        ingredients=["cam"],
        allergens=[],
        cost_per_serving_vnd=4200,
        nutrition_per_serving=NutritionInfo(calories=78, protein_g=1.2, fiber_g=2.4),
        tags=[],
    ),
    Dish(
        id="dragon_fruit",
        name="Thanh long",
        category="fruit",
        ingredients=["thanh long"],
        allergens=[],
        cost_per_serving_vnd=4100,
        nutrition_per_serving=NutritionInfo(calories=74, protein_g=1.0, fiber_g=2.8),
        tags=[],
    ),
    Dish(
        id="apple",
        name="Tao",
        category="fruit",
        ingredients=["tao"],
        allergens=[],
        cost_per_serving_vnd=4400,
        nutrition_per_serving=NutritionInfo(calories=81, protein_g=0.5, fiber_g=2.4),
        tags=[],
    ),
    Dish(
        id="watermelon",
        name="Dua hau",
        category="fruit",
        ingredients=["dua hau"],
        allergens=[],
        cost_per_serving_vnd=3900,
        nutrition_per_serving=NutritionInfo(calories=68, protein_g=0.8, fiber_g=1.9),
        tags=[],
    ),
    Dish(
        id="pear",
        name="Le",
        category="fruit",
        ingredients=["le"],
        allergens=[],
        cost_per_serving_vnd=4300,
        nutrition_per_serving=NutritionInfo(calories=85, protein_g=0.6, fiber_g=2.7),
        tags=[],
    ),
]


def get_mock_catalog() -> list[Dish]:
    return [dish.model_copy(deep=True) for dish in MOCK_CATALOG]
